source 'http://rubygems.org'

gem 'rails', '~>3.0.10'
gem 'mysql2', '0.2.7'
gem 'memcache-client'
gem 'spree', '~> 0.60.6'
gem 'spree_i18n', :git => 'git://github.com/spree/spree_i18n.git', :ref => 'a185d160047ce54f07bd47f7d417d9e2681fbb07'
gem 'synergy', '~> 0.60.0'
gem 'synergy_inventory_management', :git => 'git://github.com/secoint/synergy_inventory_management.git'
gem 'synergy_default_theme', '1.0.2'
gem 'spree_social', :git => 'git://github.com/spree/spree_social.git', :tag => 'v1.2'
gem 'spree_pretty_photo', :git => 'git://github.com/changinglanes/Spree-PrettyPhoto.git'
gem 'spree_reviews', '0.50.1'
