source 'http://rubygems.org'

gem 'mysql2', '0.2.7'
gem 'memcache-client'
#gem 'russian', :git => 'git://github.com/yaroslav/russian.git', :branch => '0.2.7'
gem 'spree', '~> 0.60.6'
gem 'spree_i18n', :git => 'git://github.com/spree/spree_i18n.git', :ref => 'a185d160047ce54f07bd47f7d417d9e2681fbb07'
gem 'synergy', '~> 0.60.0'
gem 'synergy_default_theme', '1.0.2'
#gem 'spree_static_content', '~>0.60.1'
#gem 'spree_editor'
#gem 'spree_online_support'
#gem 'spree_robokassa'
#gem 'spree_yandex_market'
#gem 'spree_address_book'
#gem 'spree_dynamic_sitemaps'
gem 'spree_social', :git => 'git://github.com/spree/spree_social.git', :tag => 'v1.2'
gem 'spree_pretty_photo', :git => 'git://github.com/changinglanes/Spree-PrettyPhoto.git' 
gem 'spree_reviews', '0.50.1'
